In [2]:


#Install Packages
!pip install faiss-cpu
!pip install sentence-transformers

Collecting faiss-cpu
  Downloading faiss_cpu-1.13.2-cp312-cp312-win_amd64.whl.metadata (7.6 kB)
Requirement already satisfied: numpy<3.0,>=1.25.0 in c:\users\raksh\anaconda3\lib\site-packages (from faiss-cpu) (1.26.4)
Requirement already satisfied: packaging in c:\users\raksh\anaconda3\lib\site-packages (from faiss-cpu) (24.1)
Downloading faiss_cpu-1.13.2-cp312-cp312-win_amd64.whl (18.9 MB)
   ---------------------------------------- 0.0/18.9 MB ? eta -:--:--
   ---------------------------------------- 0.0/18.9 MB ? eta -:--:--
   ---------------------------------------- 0.0/18.9 MB ? eta -:--:--
    --------------------------------------- 0.3/18.9 MB ? eta -:--:--
    --------------------------------------- 0.3/18.9 MB ? eta -:--:--
   - -------------------------------------- 0.5/18.9 MB 932.9 kB/s eta 0:00:20
   - -------------------------------------- 0.5/18.9 MB 932.9 kB/s eta 0:00:20
   - -------------------------------------- 0.8/18.9 MB 589.1 kB/s eta 0:00:31
   - -------------------------------------- 0.8/18.9 MB 589.1 kB/s eta 0:00:31
   - -------------------------------------- 0.8/18.9 MB 589.1 kB/s eta 0:00:31
   -- ------------------------------------- 1.0/18.9 MB 578.7 kB/s eta 0:00:31
   -- ------------------------------------- 1.3/18.9 MB 645.3 kB/s eta 0:00:28
   -- ------------------------------------- 1.3/18.9 MB 645.3 kB/s eta 0:00:28
   --- ------------------------------------ 1.6/18.9 MB 650.5 kB/s eta 0:00:27
   --- ------------------------------------ 1.8/18.9 MB 680.3 kB/s eta 0:00:26
   ---- ----------------------------------- 2.1/18.9 MB 711.8 kB/s eta 0:00:24
   ---- ----------------------------------- 2.4/18.9 MB 725.7 kB/s eta 0:00:23
   ----- ---------------------------------- 2.6/18.9 MB 774.3 kB/s eta 0:00:22
   ------ --------------------------------- 2.9/18.9 MB 810.6 kB/s eta 0:00:20
   ------ --------------------------------- 3.1/18.9 MB 846.6 kB/s eta 0:00:19
   ------- -------------------------------- 3.4/18.9 MB 879.2 kB/s eta 0:00:18
   -------- ------------------------------- 3.9/18.9 MB 921.2 kB/s eta 0:00:17
   -------- ------------------------------- 4.2/18.9 MB 946.1 kB/s eta 0:00:16
   --------- ------------------------------ 4.5/18.9 MB 972.7 kB/s eta 0:00:15
   ---------- ----------------------------- 5.0/18.9 MB 1.0 MB/s eta 0:00:14
   ----------- ---------------------------- 5.5/18.9 MB 1.1 MB/s eta 0:00:13
   ------------ --------------------------- 5.8/18.9 MB 1.1 MB/s eta 0:00:12
   ------------ --------------------------- 6.0/18.9 MB 1.1 MB/s eta 0:00:12
   ------------- -------------------------- 6.6/18.9 MB 1.1 MB/s eta 0:00:11
   -------------- ------------------------- 6.8/18.9 MB 1.2 MB/s eta 0:00:11
   -------------- ------------------------- 7.1/18.9 MB 1.2 MB/s eta 0:00:11
   ---------------- ----------------------- 7.6/18.9 MB 1.2 MB/s eta 0:00:10
   ---------------- ----------------------- 7.9/18.9 MB 1.2 MB/s eta 0:00:10
   ----------------- ---------------------- 8.1/18.9 MB 1.2 MB/s eta 0:00:09
   ------------------ --------------------- 8.7/18.9 MB 1.2 MB/s eta 0:00:09
   ------------------ --------------------- 8.9/18.9 MB 1.3 MB/s eta 0:00:08
   ------------------- -------------------- 9.2/18.9 MB 1.3 MB/s eta 0:00:08
   -------------------- ------------------- 9.7/18.9 MB 1.3 MB/s eta 0:00:08
   --------------------- ------------------ 10.0/18.9 MB 1.3 MB/s eta 0:00:08
   --------------------- ------------------ 10.2/18.9 MB 1.3 MB/s eta 0:00:07
   ---------------------- ----------------- 10.5/18.9 MB 1.3 MB/s eta 0:00:07
   ---------------------- ----------------- 10.7/18.9 MB 1.3 MB/s eta 0:00:07
   ----------------------- ---------------- 11.0/18.9 MB 1.3 MB/s eta 0:00:07
   ----------------------- ---------------- 11.3/18.9 MB 1.3 MB/s eta 0:00:06
   ------------------------ --------------- 11.5/18.9 MB 1.3 MB/s eta 0:00:06
   ------------------------ --------------- 11.8/18.9 MB 1.3 MB/s eta 0:00:06
   -------------------------- ------------- 12.3/18.9 MB 1.3 MB/s eta 0:00:06
   -------------------------- ------------- 12.6/18.9 MB 1.3 MB/s eta 0:00:05
   --------------------------- ------------ 12.8/18.9 MB 1.3 MB/s eta 0:00:05
   ---------------------------- ----------- 13.4/18.9 MB 1.3 MB/s eta 0:00:05
   ---------------------------- ----------- 13.6/18.9 MB 1.3 MB/s eta 0:00:04
   ----------------------------- ---------- 14.2/18.9 MB 1.3 MB/s eta 0:00:04
   ------------------------------ --------- 14.4/18.9 MB 1.3 MB/s eta 0:00:04
   ------------------------------- -------- 14.7/18.9 MB 1.3 MB/s eta 0:00:04
   -------------------------------- ------- 15.2/18.9 MB 1.3 MB/s eta 0:00:03
   -------------------------------- ------- 15.5/18.9 MB 1.4 MB/s eta 0:00:03
   --------------------------------- ------ 16.0/18.9 MB 1.4 MB/s eta 0:00:03
   ---------------------------------- ----- 16.3/18.9 MB 1.4 MB/s eta 0:00:02
   ---------------------------------- ----- 16.5/18.9 MB 1.4 MB/s eta 0:00:02
   ----------------------------------- ---- 16.8/18.9 MB 1.4 MB/s eta 0:00:02
   ------------------------------------ --- 17.3/18.9 MB 1.4 MB/s eta 0:00:02
   ------------------------------------- -- 17.6/18.9 MB 1.4 MB/s eta 0:00:01
   ------------------------------------- -- 17.8/18.9 MB 1.4 MB/s eta 0:00:01
   -------------------------------------- - 18.1/18.9 MB 1.4 MB/s eta 0:00:01
   -------------------------------------- - 18.4/18.9 MB 1.4 MB/s eta 0:00:01
   ---------------------------------------  18.6/18.9 MB 1.4 MB/s eta 0:00:01
   ---------------------------------------- 18.9/18.9 MB 1.4 MB/s eta 0:00:00
Installing collected packages: faiss-cpu
Successfully installed faiss-cpu-1.13.2
Collecting sentence-transformers
  Downloading sentence_transformers-5.2.0-py3-none-any.whl.metadata (16 kB)
Collecting transformers<6.0.0,>=4.41.0 (from sentence-transformers)
  Downloading transformers-4.57.3-py3-none-any.whl.metadata (43 kB)
Requirement already satisfied: tqdm in c:\users\raksh\anaconda3\lib\site-packages (from sentence-transformers) (4.66.5)
Collecting torch>=1.11.0 (from sentence-transformers)
  Downloading torch-2.9.1-cp312-cp312-win_amd64.whl.metadata (30 kB)
Requirement already satisfied: scikit-learn in c:\users\raksh\anaconda3\lib\site-packages (from sentence-transformers) (1.5.1)
Requirement already satisfied: scipy in c:\users\raksh\anaconda3\lib\site-packages (from sentence-transformers) (1.13.1)
Collecting huggingface-hub>=0.20.0 (from sentence-transformers)
  Downloading huggingface_hub-1.2.3-py3-none-any.whl.metadata (13 kB)
Requirement already satisfied: typing_extensions>=4.5.0 in c:\users\raksh\anaconda3\lib\site-packages (from sentence-transformers) (4.15.0)
Requirement already satisfied: filelock in c:\users\raksh\anaconda3\lib\site-packages (from huggingface-hub>=0.20.0->sentence-transformers) (3.13.1)
Requirement already satisfied: fsspec>=2023.5.0 in c:\users\raksh\anaconda3\lib\site-packages (from huggingface-hub>=0.20.0->sentence-transformers) (2024.6.1)
Collecting hf-xet<2.0.0,>=1.2.0 (from huggingface-hub>=0.20.0->sentence-transformers)
  Downloading hf_xet-1.2.0-cp37-abi3-win_amd64.whl.metadata (5.0 kB)
Requirement already satisfied: httpx<1,>=0.23.0 in c:\users\raksh\anaconda3\lib\site-packages (from huggingface-hub>=0.20.0->sentence-transformers) (0.27.0)
Requirement already satisfied: packaging>=20.9 in c:\users\raksh\anaconda3\lib\site-packages (from huggingface-hub>=0.20.0->sentence-transformers) (24.1)
Requirement already satisfied: pyyaml>=5.1 in c:\users\raksh\anaconda3\lib\site-packages (from huggingface-hub>=0.20.0->sentence-transformers) (6.0.1)
Requirement already satisfied: shellingham in c:\users\raksh\anaconda3\lib\site-packages (from huggingface-hub>=0.20.0->sentence-transformers) (1.5.0)
Collecting typer-slim (from huggingface-hub>=0.20.0->sentence-transformers)
  Downloading typer_slim-0.21.0-py3-none-any.whl.metadata (16 kB)
Collecting sympy>=1.13.3 (from torch>=1.11.0->sentence-transformers)
  Downloading sympy-1.14.0-py3-none-any.whl.metadata (12 kB)
Requirement already satisfied: networkx>=2.5.1 in c:\users\raksh\anaconda3\lib\site-packages (from torch>=1.11.0->sentence-transformers) (3.3)
Requirement already satisfied: jinja2 in c:\users\raksh\anaconda3\lib\site-packages (from torch>=1.11.0->sentence-transformers) (3.1.4)
Requirement already satisfied: setuptools in c:\users\raksh\anaconda3\lib\site-packages (from torch>=1.11.0->sentence-transformers) (75.1.0)
Requirement already satisfied: colorama in c:\users\raksh\anaconda3\lib\site-packages (from tqdm->sentence-transformers) (0.4.6)
Collecting huggingface-hub>=0.20.0 (from sentence-transformers)
  Downloading huggingface_hub-0.36.0-py3-none-any.whl.metadata (14 kB)
Requirement already satisfied: numpy>=1.17 in c:\users\raksh\anaconda3\lib\site-packages (from transformers<6.0.0,>=4.41.0->sentence-transformers) (1.26.4)
Requirement already satisfied: regex!=2019.12.17 in c:\users\raksh\anaconda3\lib\site-packages (from transformers<6.0.0,>=4.41.0->sentence-transformers) (2024.9.11)
Requirement already satisfied: requests in c:\users\raksh\anaconda3\lib\site-packages (from transformers<6.0.0,>=4.41.0->sentence-transformers) (2.32.3)
Collecting tokenizers<=0.23.0,>=0.22.0 (from transformers<6.0.0,>=4.41.0->sentence-transformers)
  Downloading tokenizers-0.22.1-cp39-abi3-win_amd64.whl.metadata (6.9 kB)
Collecting safetensors>=0.4.3 (from transformers<6.0.0,>=4.41.0->sentence-transformers)
  Downloading safetensors-0.7.0-cp38-abi3-win_amd64.whl.metadata (4.2 kB)
Requirement already satisfied: joblib>=1.2.0 in c:\users\raksh\anaconda3\lib\site-packages (from scikit-learn->sentence-transformers) (1.4.2)
Requirement already satisfied: threadpoolctl>=3.1.0 in c:\users\raksh\anaconda3\lib\site-packages (from scikit-learn->sentence-transformers) (3.5.0)
Requirement already satisfied: mpmath<1.4,>=1.1.0 in c:\users\raksh\anaconda3\lib\site-packages (from sympy>=1.13.3->torch>=1.11.0->sentence-transformers) (1.3.0)
Requirement already satisfied: MarkupSafe>=2.0 in c:\users\raksh\anaconda3\lib\site-packages (from jinja2->torch>=1.11.0->sentence-transformers) (2.1.3)
Requirement already satisfied: charset-normalizer<4,>=2 in c:\users\raksh\anaconda3\lib\site-packages (from requests->transformers<6.0.0,>=4.41.0->sentence-transformers) (3.3.2)
Requirement already satisfied: idna<4,>=2.5 in c:\users\raksh\anaconda3\lib\site-packages (from requests->transformers<6.0.0,>=4.41.0->sentence-transformers) (3.7)
Requirement already satisfied: urllib3<3,>=1.21.1 in c:\users\raksh\anaconda3\lib\site-packages (from requests->transformers<6.0.0,>=4.41.0->sentence-transformers) (2.2.3)
Requirement already satisfied: certifi>=2017.4.17 in c:\users\raksh\anaconda3\lib\site-packages (from requests->transformers<6.0.0,>=4.41.0->sentence-transformers) (2025.1.31)
Requirement already satisfied: anyio in c:\users\raksh\anaconda3\lib\site-packages (from httpx<1,>=0.23.0->huggingface-hub>=0.20.0->sentence-transformers) (4.2.0)
Requirement already satisfied: httpcore==1.* in c:\users\raksh\anaconda3\lib\site-packages (from httpx<1,>=0.23.0->huggingface-hub>=0.20.0->sentence-transformers) (1.0.9)
Requirement already satisfied: sniffio in c:\users\raksh\anaconda3\lib\site-packages (from httpx<1,>=0.23.0->huggingface-hub>=0.20.0->sentence-transformers) (1.3.0)
Requirement already satisfied: h11>=0.16 in c:\users\raksh\anaconda3\lib\site-packages (from httpcore==1.*->httpx<1,>=0.23.0->huggingface-hub>=0.20.0->sentence-transformers) (0.16.0)
Requirement already satisfied: click>=8.0.0 in c:\users\raksh\anaconda3\lib\site-packages (from typer-slim->huggingface-hub>=0.20.0->sentence-transformers) (8.1.7)
Downloading sentence_transformers-5.2.0-py3-none-any.whl (493 kB)
Downloading torch-2.9.1-cp312-cp312-win_amd64.whl (110.9 MB)
   ---------------------------------------- 0.0/110.9 MB ? eta -:--:--
   ---------------------------------------- 0.3/110.9 MB ? eta -:--:--
   ---------------------------------------- 0.5/110.9 MB 2.1 MB/s eta 0:00:53
   ---------------------------------------- 1.0/110.9 MB 1.9 MB/s eta 0:00:57
    --------------------------------------- 1.6/110.9 MB 2.2 MB/s eta 0:00:50
    --------------------------------------- 2.1/110.9 MB 2.2 MB/s eta 0:00:51
    --------------------------------------- 2.4/110.9 MB 2.2 MB/s eta 0:00:51
    --------------------------------------- 2.6/110.9 MB 2.1 MB/s eta 0:00:52
   - -------------------------------------- 2.9/110.9 MB 2.0 MB/s eta 0:00:56
   - -------------------------------------- 3.1/110.9 MB 1.8 MB/s eta 0:01:01
   - -------------------------------------- 3.7/110.9 MB 1.7 MB/s eta 0:01:02
   - -------------------------------------- 3.9/110.9 MB 1.8 MB/s eta 0:01:02
   - -------------------------------------- 4.2/110.9 MB 1.7 MB/s eta 0:01:02
   - -------------------------------------- 4.7/110.9 MB 1.7 MB/s eta 0:01:01
   - -------------------------------------- 5.2/110.9 MB 1.8 MB/s eta 0:01:00
   - -------------------------------------- 5.5/110.9 MB 1.8 MB/s eta 0:01:01
   -- ------------------------------------- 5.8/110.9 MB 1.7 MB/s eta 0:01:01
   -- ------------------------------------- 6.3/110.9 MB 1.8 MB/s eta 0:01:00
   -- ------------------------------------- 6.6/110.9 MB 1.8 MB/s eta 0:01:00
   -- ------------------------------------- 7.1/110.9 MB 1.8 MB/s eta 0:01:00
   -- ------------------------------------- 7.1/110.9 MB 1.8 MB/s eta 0:01:00
   -- ------------------------------------- 7.3/110.9 MB 1.7 MB/s eta 0:01:02
   -- ------------------------------------- 7.6/110.9 MB 1.7 MB/s eta 0:01:03
   -- ------------------------------------- 7.9/110.9 MB 1.6 MB/s eta 0:01:04
   -- ------------------------------------- 8.1/110.9 MB 1.6 MB/s eta 0:01:04
   --- ------------------------------------ 8.4/110.9 MB 1.6 MB/s eta 0:01:04
   --- ------------------------------------ 8.9/110.9 MB 1.6 MB/s eta 0:01:04
   --- ------------------------------------ 9.2/110.9 MB 1.6 MB/s eta 0:01:04
   --- ------------------------------------ 9.7/110.9 MB 1.6 MB/s eta 0:01:03
   --- ------------------------------------ 10.0/110.9 MB 1.6 MB/s eta 0:01:02
   --- ------------------------------------ 10.5/110.9 MB 1.6 MB/s eta 0:01:02
   --- ------------------------------------ 10.7/110.9 MB 1.6 MB/s eta 0:01:02
   --- ------------------------------------ 11.0/110.9 MB 1.6 MB/s eta 0:01:02
   ---- ----------------------------------- 11.3/110.9 MB 1.6 MB/s eta 0:01:02
   ---- ----------------------------------- 11.5/110.9 MB 1.6 MB/s eta 0:01:03
   ---- ----------------------------------- 11.8/110.9 MB 1.6 MB/s eta 0:01:03
   ---- ----------------------------------- 12.1/110.9 MB 1.6 MB/s eta 0:01:04
   ---- ----------------------------------- 12.3/110.9 MB 1.5 MB/s eta 0:01:04
   ---- ----------------------------------- 12.3/110.9 MB 1.5 MB/s eta 0:01:04
   ---- ----------------------------------- 12.3/110.9 MB 1.5 MB/s eta 0:01:04
   ---- ----------------------------------- 12.6/110.9 MB 1.5 MB/s eta 0:01:07
   ---- ----------------------------------- 12.6/110.9 MB 1.5 MB/s eta 0:01:07
   ---- ----------------------------------- 12.8/110.9 MB 1.4 MB/s eta 0:01:08
   ---- ----------------------------------- 13.1/110.9 MB 1.4 MB/s eta 0:01:08
   ---- ----------------------------------- 13.4/110.9 MB 1.4 MB/s eta 0:01:09
   ---- ----------------------------------- 13.6/110.9 MB 1.4 MB/s eta 0:01:09
   ----- ---------------------------------- 13.9/110.9 MB 1.4 MB/s eta 0:01:09
   ----- ---------------------------------- 14.2/110.9 MB 1.4 MB/s eta 0:01:09
   ----- ---------------------------------- 14.4/110.9 MB 1.4 MB/s eta 0:01:09
   ----- ---------------------------------- 14.7/110.9 MB 1.4 MB/s eta 0:01:09
   ----- ---------------------------------- 14.9/110.9 MB 1.4 MB/s eta 0:01:09
   ----- ---------------------------------- 15.2/110.9 MB 1.4 MB/s eta 0:01:09
   ----- ---------------------------------- 15.5/110.9 MB 1.4 MB/s eta 0:01:09
   ----- ---------------------------------- 15.7/110.9 MB 1.4 MB/s eta 0:01:09
   ----- ---------------------------------- 16.0/110.9 MB 1.4 MB/s eta 0:01:09
   ----- ---------------------------------- 16.3/110.9 MB 1.4 MB/s eta 0:01:09
   ----- ---------------------------------- 16.5/110.9 MB 1.4 MB/s eta 0:01:09
   ------ --------------------------------- 16.8/110.9 MB 1.4 MB/s eta 0:01:09
   ------ --------------------------------- 17.0/110.9 MB 1.4 MB/s eta 0:01:08
   ------ --------------------------------- 17.3/110.9 MB 1.4 MB/s eta 0:01:09
   ------ --------------------------------- 17.6/110.9 MB 1.4 MB/s eta 0:01:09
   ------ --------------------------------- 17.8/110.9 MB 1.4 MB/s eta 0:01:09
   ------ --------------------------------- 18.1/110.9 MB 1.4 MB/s eta 0:01:08
   ------ --------------------------------- 18.4/110.9 MB 1.4 MB/s eta 0:01:08
   ------ --------------------------------- 18.6/110.9 MB 1.4 MB/s eta 0:01:08
   ------ --------------------------------- 18.9/110.9 MB 1.4 MB/s eta 0:01:08
   ------ --------------------------------- 19.1/110.9 MB 1.4 MB/s eta 0:01:08
   ------ --------------------------------- 19.4/110.9 MB 1.4 MB/s eta 0:01:08
   ------ --------------------------------- 19.4/110.9 MB 1.4 MB/s eta 0:01:08
   ------- -------------------------------- 19.7/110.9 MB 1.3 MB/s eta 0:01:09
   ------- -------------------------------- 19.9/110.9 MB 1.3 MB/s eta 0:01:09
   ------- -------------------------------- 20.2/110.9 MB 1.3 MB/s eta 0:01:09
   ------- -------------------------------- 20.4/110.9 MB 1.3 MB/s eta 0:01:09
   ------- -------------------------------- 20.7/110.9 MB 1.3 MB/s eta 0:01:09
   ------- -------------------------------- 20.7/110.9 MB 1.3 MB/s eta 0:01:09
   ------- -------------------------------- 21.2/110.9 MB 1.3 MB/s eta 0:01:09
   ------- -------------------------------- 21.5/110.9 MB 1.3 MB/s eta 0:01:09
   ------- -------------------------------- 21.8/110.9 MB 1.3 MB/s eta 0:01:08
   ------- -------------------------------- 22.0/110.9 MB 1.3 MB/s eta 0:01:08
   -------- ------------------------------- 22.3/110.9 MB 1.3 MB/s eta 0:01:08
   -------- ------------------------------- 22.5/110.9 MB 1.3 MB/s eta 0:01:08
   -------- ------------------------------- 22.8/110.9 MB 1.3 MB/s eta 0:01:08
   -------- ------------------------------- 23.1/110.9 MB 1.3 MB/s eta 0:01:08
   -------- ------------------------------- 23.6/110.9 MB 1.3 MB/s eta 0:01:07
   -------- ------------------------------- 23.9/110.9 MB 1.3 MB/s eta 0:01:06
   -------- ------------------------------- 24.1/110.9 MB 1.3 MB/s eta 0:01:06
   -------- ------------------------------- 24.6/110.9 MB 1.3 MB/s eta 0:01:05
   -------- ------------------------------- 24.9/110.9 MB 1.3 MB/s eta 0:01:05
   --------- ------------------------------ 25.4/110.9 MB 1.3 MB/s eta 0:01:04
   --------- ------------------------------ 25.7/110.9 MB 1.3 MB/s eta 0:01:04
   --------- ------------------------------ 26.2/110.9 MB 1.4 MB/s eta 0:01:03
   --------- ------------------------------ 26.5/110.9 MB 1.4 MB/s eta 0:01:03
   --------- ------------------------------ 27.0/110.9 MB 1.4 MB/s eta 0:01:02
   --------- ------------------------------ 27.3/110.9 MB 1.4 MB/s eta 0:01:02
   --------- ------------------------------ 27.5/110.9 MB 1.4 MB/s eta 0:01:01
   ---------- ----------------------------- 27.8/110.9 MB 1.4 MB/s eta 0:01:01
   ---------- ----------------------------- 28.0/110.9 MB 1.4 MB/s eta 0:01:01
   ---------- ----------------------------- 28.3/110.9 MB 1.4 MB/s eta 0:01:01
   ---------- ----------------------------- 28.8/110.9 MB 1.4 MB/s eta 0:01:00
   ---------- ----------------------------- 29.1/110.9 MB 1.4 MB/s eta 0:01:00
   ---------- ----------------------------- 29.6/110.9 MB 1.4 MB/s eta 0:01:00
   ---------- ----------------------------- 29.9/110.9 MB 1.4 MB/s eta 0:00:59
   ---------- ----------------------------- 30.1/110.9 MB 1.4 MB/s eta 0:00:59
   ----------- ---------------------------- 30.7/110.9 MB 1.4 MB/s eta 0:00:58

In [3]:
import pandas as pd
pd.set_option('display.max_colwidth', 100)

In [4]:
df = pd.read_csv("sample_text.csv")
df.shape

FileNotFoundError: [Errno 2] No such file or directory: 'sample_text.csv'

In [6]:
import os
os.getcwd()

'C:\\Users\\raksh'

In [8]:
import pandas as pd

data = {
    "text": [
        "NVIDIA stock fell 3.56% today but gained 32.35% over 3 months.",
        "EPS of NVIDIA is $1.92, raising valuation questions."
    ]
}

df = pd.DataFrame(data)
df.to_csv("sample_text.csv", index=False)

print("CSV file created successfully")

CSV file created successfully

In [10]:
import pandas as pd

df = pd.read_csv("sample_text.csv")
print(df.shape)
print(df.head())

(2, 1)
                                                             text
0  NVIDIA stock fell 3.56% today but gained 32.35% over 3 months.
1            EPS of NVIDIA is $1.92, raising valuation questions.

In [12]:
df = pd.read_csv("sample_text.csv")
df.shape

(2, 1)

In [14]:
df

                                                             text
0  NVIDIA stock fell 3.56% today but gained 32.35% over 3 months.
1            EPS of NVIDIA is $1.92, raising valuation questions.

In [16]:
import pandas as pd

df = pd.read_csv("/mnt/data/sample_text.csv")
print(df.shape)
print(df.head())

FileNotFoundError: [Errno 2] No such file or directory: '/mnt/data/sample_text.csv'

In [18]:
import pandas as pd

data = {
    "Text": [
        "Meditation and yoga can improve mental health",
        "Fruits, whole grains and vegetables helps control blood pressure",
        "These are the latest fashion trends for this week",
        "Vibrant color jeans for male are becoming a trend",
        "The concert starts at 7 PM tonight",
        "Navaratri dandiya program at Expo center in Mumbai this october",
        "Exciting vacation destinations for your next trip",
        "Maldives and Srilanka are gaining popularity in terms of low budget vacation places"
    ],
    "Category": [
        "Health",
        "Health",
        "Fashion",
        "Fashion",
        "Event",
        "Event",
        "Travel",
        "Travel"
    ]
}

df = pd.DataFrame(data)
df.to_csv("sample_text.csv", index=True)

print("sample_text.csv created successfully")

sample_text.csv created successfully

In [20]:
import pandas as pd

df = pd.read_csv("sample_text.csv")
print(df)

   Unnamed: 0  \
0           0
1           1
2           2
3           3
4           4
5           5
6           6
7           7

                                                                                  Text  \
0                                        Meditation and yoga can improve mental health
1                     Fruits, whole grains and vegetables helps control blood pressure
2                                    These are the latest fashion trends for this week
3                                    Vibrant color jeans for male are becoming a trend
4                                                   The concert starts at 7 PM tonight
5                      Navaratri dandiya program at Expo center in Mumbai this october
6                                    Exciting vacation destinations for your next trip
7  Maldives and Srilanka are gaining popularity in terms of low budget vacation places

  Category
0   Health
1   Health
2  Fashion
3  Fashion
4    Event
5    Event
6   Travel
7   Travel

In [22]:
df

,Unnamed: 0,Text,Category
0,0,Meditation and yoga can improve mental health,Health
1,1,"Fruits, whole grains and vegetables helps control blood pressure",Health
2,2,These are the latest fashion trends for this week,Fashion
3,3,Vibrant color jeans for male are becoming a trend,Fashion
4,4,The concert starts at 7 PM tonight,Event
5,5,Navaratri dandiya program at Expo center in Mumbai this october,Event
6,6,Exciting vacation destinations for your next trip,Travel
7,7,Maldives and Srilanka are gaining popularity in terms of low budget vacation places,Travel

In [24]:


from sentence_transformers import SentenceTransformer

In [ ]:


encoder = SentenceTransformer("all-mpnet-base-v2")
vectors = encoder.encode(df.text)

modules.json:   0%|          | 0.00/349 [00:00<?, ?B/s]

C:\Users\raksh\anaconda3\Lib\site-packages\huggingface_hub\file_download.py:143: UserWarning: `huggingface_hub` cache-system uses symlinks by default to efficiently store duplicated files but your machine does not support them in C:\Users\raksh\.cache\huggingface\hub\models--sentence-transformers--all-mpnet-base-v2. Caching files will still work but in a degraded version that might require more space on your disk. This warning can be disabled by setting the `HF_HUB_DISABLE_SYMLINKS_WARNING` environment variable. For more details, see https://huggingface.co/docs/huggingface_hub/how-to-cache#limitations.
To support symlinks on Windows, you either need to activate Developer Mode or to run Python as an administrator. In order to activate developer mode, see this article: https://docs.microsoft.com/en-us/windows/apps/get-started/enable-your-device-for-development
  warnings.warn(message)

config_sentence_transformers.json:   0%|          | 0.00/116 [00:00<?, ?B/s]

README.md: 0.00B [00:00, ?B/s]

sentence_bert_config.json:   0%|          | 0.00/53.0 [00:00<?, ?B/s]

config.json:   0%|          | 0.00/571 [00:00<?, ?B/s]

Xet Storage is enabled for this repo, but the 'hf_xet' package is not installed. Falling back to regular HTTP download. For better performance, install the package with: `pip install huggingface_hub[hf_xet]` or `pip install hf_xet`

model.safetensors:   0%|          | 0.00/438M [00:00<?, ?B/s]

In [1]:
pip install ipywidgets

Requirement already satisfied: ipywidgets in c:\users\raksh\anaconda3\lib\site-packages (7.8.1)
Requirement already satisfied: comm>=0.1.3 in c:\users\raksh\anaconda3\lib\site-packages (from ipywidgets) (0.2.1)
Requirement already satisfied: ipython-genutils~=0.2.0 in c:\users\raksh\anaconda3\lib\site-packages (from ipywidgets) (0.2.0)
Requirement already satisfied: traitlets>=4.3.1 in c:\users\raksh\anaconda3\lib\site-packages (from ipywidgets) (5.14.3)
Requirement already satisfied: widgetsnbextension~=3.6.6 in c:\users\raksh\anaconda3\lib\site-packages (from ipywidgets) (3.6.6)
Requirement already satisfied: ipython>=4.0.0 in c:\users\raksh\anaconda3\lib\site-packages (from ipywidgets) (8.27.0)
Requirement already satisfied: jupyterlab-widgets<3,>=1.0.0 in c:\users\raksh\anaconda3\lib\site-packages (from ipywidgets) (1.0.0)
Requirement already satisfied: decorator in c:\users\raksh\anaconda3\lib\site-packages (from ipython>=4.0.0->ipywidgets) (5.1.1)
Requirement already satisfied: jedi>=0.16 in c:\users\raksh\anaconda3\lib\site-packages (from ipython>=4.0.0->ipywidgets) (0.19.1)
Requirement already satisfied: matplotlib-inline in c:\users\raksh\anaconda3\lib\site-packages (from ipython>=4.0.0->ipywidgets) (0.1.6)
Requirement already satisfied: prompt-toolkit<3.1.0,>=3.0.41 in c:\users\raksh\anaconda3\lib\site-packages (from ipython>=4.0.0->ipywidgets) (3.0.43)
Requirement already satisfied: pygments>=2.4.0 in c:\users\raksh\anaconda3\lib\site-packages (from ipython>=4.0.0->ipywidgets) (2.15.1)
Requirement already satisfied: stack-data in c:\users\raksh\anaconda3\lib\site-packages (from ipython>=4.0.0->ipywidgets) (0.2.0)
Requirement already satisfied: colorama in c:\users\raksh\anaconda3\lib\site-packages (from ipython>=4.0.0->ipywidgets) (0.4.6)
Requirement already satisfied: notebook>=4.4.1 in c:\users\raksh\anaconda3\lib\site-packages (from widgetsnbextension~=3.6.6->ipywidgets) (7.2.2)
Requirement already satisfied: parso<0.9.0,>=0.8.3 in c:\users\raksh\anaconda3\lib\site-packages (from jedi>=0.16->ipython>=4.0.0->ipywidgets) (0.8.3)
Requirement already satisfied: jupyter-server<3,>=2.4.0 in c:\users\raksh\anaconda3\lib\site-packages (from notebook>=4.4.1->widgetsnbextension~=3.6.6->ipywidgets) (2.14.1)
Requirement already satisfied: jupyterlab-server<3,>=2.27.1 in c:\users\raksh\anaconda3\lib\site-packages (from notebook>=4.4.1->widgetsnbextension~=3.6.6->ipywidgets) (2.27.3)
Requirement already satisfied: jupyterlab<4.3,>=4.2.0 in c:\users\raksh\anaconda3\lib\site-packages (from notebook>=4.4.1->widgetsnbextension~=3.6.6->ipywidgets) (4.2.5)
Requirement already satisfied: notebook-shim<0.3,>=0.2 in c:\users\raksh\anaconda3\lib\site-packages (from notebook>=4.4.1->widgetsnbextension~=3.6.6->ipywidgets) (0.2.3)
Requirement already satisfied: tornado>=6.2.0 in c:\users\raksh\anaconda3\lib\site-packages (from notebook>=4.4.1->widgetsnbextension~=3.6.6->ipywidgets) (6.4.1)
Requirement already satisfied: wcwidth in c:\users\raksh\anaconda3\lib\site-packages (from prompt-toolkit<3.1.0,>=3.0.41->ipython>=4.0.0->ipywidgets) (0.2.5)
Requirement already satisfied: executing in c:\users\raksh\anaconda3\lib\site-packages (from stack-data->ipython>=4.0.0->ipywidgets) (0.8.3)
Requirement already satisfied: asttokens in c:\users\raksh\anaconda3\lib\site-packages (from stack-data->ipython>=4.0.0->ipywidgets) (2.0.5)
Requirement already satisfied: pure-eval in c:\users\raksh\anaconda3\lib\site-packages (from stack-data->ipython>=4.0.0->ipywidgets) (0.2.2)
Requirement already satisfied: anyio>=3.1.0 in c:\users\raksh\anaconda3\lib\site-packages (from jupyter-server<3,>=2.4.0->notebook>=4.4.1->widgetsnbextension~=3.6.6->ipywidgets) (4.2.0)
Requirement already satisfied: argon2-cffi>=21.1 in c:\users\raksh\anaconda3\lib\site-packages (from jupyter-server<3,>=2.4.0->notebook>=4.4.1->widgetsnbextension~=3.6.6->ipywidgets) (21.3.0)
Requirement already satisfied: jinja2>=3.0.3 in c:\users\raksh\anaconda3\lib\site-packages (from jupyter-server<3,>=2.4.0->notebook>=4.4.1->widgetsnbextension~=3.6.6->ipywidgets) (3.1.4)
Requirement already satisfied: jupyter-client>=7.4.4 in c:\users\raksh\anaconda3\lib\site-packages (from jupyter-server<3,>=2.4.0->notebook>=4.4.1->widgetsnbextension~=3.6.6->ipywidgets) (8.6.0)
Requirement already satisfied: jupyter-core!=5.0.*,>=4.12 in c:\users\raksh\anaconda3\lib\site-packages (from jupyter-server<3,>=2.4.0->notebook>=4.4.1->widgetsnbextension~=3.6.6->ipywidgets) (5.7.2)
Requirement already satisfied: jupyter-events>=0.9.0 in c:\users\raksh\anaconda3\lib\site-packages (from jupyter-server<3,>=2.4.0->notebook>=4.4.1->widgetsnbextension~=3.6.6->ipywidgets) (0.10.0)
Requirement already satisfied: jupyter-server-terminals>=0.4.4 in c:\users\raksh\anaconda3\lib\site-packages (from jupyter-server<3,>=2.4.0->notebook>=4.4.1->widgetsnbextension~=3.6.6->ipywidgets) (0.4.4)
Requirement already satisfied: nbconvert>=6.4.4 in c:\users\raksh\anaconda3\lib\site-packages (from jupyter-server<3,>=2.4.0->notebook>=4.4.1->widgetsnbextension~=3.6.6->ipywidgets) (7.16.4)
Requirement already satisfied: nbformat>=5.3.0 in c:\users\raksh\anaconda3\lib\site-packages (from jupyter-server<3,>=2.4.0->notebook>=4.4.1->widgetsnbextension~=3.6.6->ipywidgets) (5.10.4)
Requirement already satisfied: overrides>=5.0 in c:\users\raksh\anaconda3\lib\site-packages (from jupyter-server<3,>=2.4.0->notebook>=4.4.1->widgetsnbextension~=3.6.6->ipywidgets) (7.4.0)
Requirement already satisfied: packaging>=22.0 in c:\users\raksh\anaconda3\lib\site-packages (from jupyter-server<3,>=2.4.0->notebook>=4.4.1->widgetsnbextension~=3.6.6->ipywidgets) (24.1)
Requirement already satisfied: prometheus-client>=0.9 in c:\users\raksh\anaconda3\lib\site-packages (from jupyter-server<3,>=2.4.0->notebook>=4.4.1->widgetsnbextension~=3.6.6->ipywidgets) (0.14.1)
Requirement already satisfied: pywinpty>=2.0.1 in c:\users\raksh\anaconda3\lib\site-packages (from jupyter-server<3,>=2.4.0->notebook>=4.4.1->widgetsnbextension~=3.6.6->ipywidgets) (2.0.10)
Requirement already satisfied: pyzmq>=24 in c:\users\raksh\anaconda3\lib\site-packages (from jupyter-server<3,>=2.4.0->notebook>=4.4.1->widgetsnbextension~=3.6.6->ipywidgets) (25.1.2)
Requirement already satisfied: send2trash>=1.8.2 in c:\users\raksh\anaconda3\lib\site-packages (from jupyter-server<3,>=2.4.0->notebook>=4.4.1->widgetsnbextension~=3.6.6->ipywidgets) (1.8.2)
Requirement already satisfied: terminado>=0.8.3 in c:\users\raksh\anaconda3\lib\site-packages (from jupyter-server<3,>=2.4.0->notebook>=4.4.1->widgetsnbextension~=3.6.6->ipywidgets) (0.17.1)
Requirement already satisfied: websocket-client>=1.7 in c:\users\raksh\anaconda3\lib\site-packages (from jupyter-server<3,>=2.4.0->notebook>=4.4.1->widgetsnbextension~=3.6.6->ipywidgets) (1.8.0)
Requirement already satisfied: async-lru>=1.0.0 in c:\users\raksh\anaconda3\lib\site-packages (from jupyterlab<4.3,>=4.2.0->notebook>=4.4.1->widgetsnbextension~=3.6.6->ipywidgets) (2.0.4)
Requirement already satisfied: httpx>=0.25.0 in c:\users\raksh\anaconda3\lib\site-packages (from jupyterlab<4.3,>=4.2.0->notebook>=4.4.1->widgetsnbextension~=3.6.6->ipywidgets) (0.27.0)
Requirement already satisfied: ipykernel>=6.5.0 in c:\users\raksh\anaconda3\lib\site-packages (from jupyterlab<4.3,>=4.2.0->notebook>=4.4.1->widgetsnbextension~=3.6.6->ipywidgets) (6.28.0)
Requirement already satisfied: jupyter-lsp>=2.0.0 in c:\users\raksh\anaconda3\lib\site-packages (from jupyterlab<4.3,>=4.2.0->notebook>=4.4.1->widgetsnbextension~=3.6.6->ipywidgets) (2.2.0)
Requirement already satisfied: setuptools>=40.1.0 in c:\users\raksh\anaconda3\lib\site-packages (from jupyterlab<4.3,>=4.2.0->notebook>=4.4.1->widgetsnbextension~=3.6.6->ipywidgets) (75.1.0)
Requirement already satisfied: babel>=2.10 in c:\users\raksh\anaconda3\lib\site-packages (from jupyterlab-server<3,>=2.27.1->notebook>=4.4.1->widgetsnbextension~=3.6.6->ipywidgets) (2.11.0)
Requirement already satisfied: json5>=0.9.0 in c:\users\raksh\anaconda3\lib\site-packages (from jupyterlab-server<3,>=2.27.1->notebook>=4.4.1->widgetsnbextension~=3.6.6->ipywidgets) (0.9.6)
Requirement already satisfied: jsonschema>=4.18.0 in c:\users\raksh\anaconda3\lib\site-packages (from jupyterlab-server<3,>=2.27.1->notebook>=4.4.1->widgetsnbextension~=3.6.6->ipywidgets) (4.23.0)
Requirement already satisfied: requests>=2.31 in c:\users\raksh\anaconda3\lib\site-packages (from jupyterlab-server<3,>=2.27.1->notebook>=4.4.1->widgetsnbextension~=3.6.6->ipywidgets) (2.32.3)
Requirement already satisfied: six in c:\users\raksh\anaconda3\lib\site-packages (from asttokens->stack-data->ipython>=4.0.0->ipywidgets) (1.16.0)
Requirement already satisfied: idna>=2.8 in c:\users\raksh\anaconda3\lib\site-packages (from anyio>=3.1.0->jupyter-server<3,>=2.4.0->notebook>=4.4.1->widgetsnbextension~=3.6.6->ipywidgets) (3.7)
Requirement already satisfied: sniffio>=1.1 in c:\users\raksh\anaconda3\lib\site-packages (from anyio>=3.1.0->jupyter-server<3,>=2.4.0->notebook>=4.4.1->widgetsnbextension~=3.6.6->ipywidgets) (1.3.0)
Requirement already satisfied: argon2-cffi-bindings in c:\users\raksh\anaconda3\lib\site-packages (from argon2-cffi>=21.1->jupyter-server<3,>=2.4.0->notebook>=4.4.1->widgetsnbextension~=3.6.6->ipywidgets) (21.2.0)
Requirement already satisfied: pytz>=2015.7 in c:\users\raksh\anaconda3\lib\site-packages (from babel>=2.10->jupyterlab-server<3,>=2.27.1->notebook>=4.4.1->widgetsnbextension~=3.6.6->ipywidgets) (2024.1)
Requirement already satisfied: certifi in c:\users\raksh\anaconda3\lib\site-packages (from httpx>=0.25.0->jupyterlab<4.3,>=4.2.0->notebook>=4.4.1->widgetsnbextension~=3.6.6->ipywidgets) (2025.1.31)
Requirement already satisfied: httpcore==1.* in c:\users\raksh\anaconda3\lib\site-packages (from httpx>=0.25.0->jupyterlab<4.3,>=4.2.0->notebook>=4.4.1->widgetsnbextension~=3.6.6->ipywidgets) (1.0.9)
Requirement already satisfied: h11>=0.16 in c:\users\raksh\anaconda3\lib\site-packages (from httpcore==1.*->httpx>=0.25.0->jupyterlab<4.3,>=4.2.0->notebook>=4.4.1->widgetsnbextension~=3.6.6->ipywidgets) (0.16.0)
Requirement already satisfied: debugpy>=1.6.5 in c:\users\raksh\anaconda3\lib\site-packages (from ipykernel>=6.5.0->jupyterlab<4.3,>=4.2.0->notebook>=4.4.1->widgetsnbextension~=3.6.6->ipywidgets) (1.6.7)
Requirement already satisfied: nest-asyncio in c:\users\raksh\anaconda3\lib\site-packages (from ipykernel>=6.5.0->jupyterlab<4.3,>=4.2.0->notebook>=4.4.1->widgetsnbextension~=3.6.6->ipywidgets) (1.6.0)
Requirement already satisfied: psutil in c:\users\raksh\anaconda3\lib\site-packages (from ipykernel>=6.5.0->jupyterlab<4.3,>=4.2.0->notebook>=4.4.1->widgetsnbextension~=3.6.6->ipywidgets) (5.9.0)
Requirement already satisfied: MarkupSafe>=2.0 in c:\users\raksh\anaconda3\lib\site-packages (from jinja2>=3.0.3->jupyter-server<3,>=2.4.0->notebook>=4.4.1->widgetsnbextension~=3.6.6->ipywidgets) (2.1.3)
Requirement already satisfied: attrs>=22.2.0 in c:\users\raksh\anaconda3\lib\site-packages (from jsonschema>=4.18.0->jupyterlab-server<3,>=2.27.1->notebook>=4.4.1->widgetsnbextension~=3.6.6->ipywidgets) (23.1.0)
Requirement already satisfied: jsonschema-specifications>=2023.03.6 in c:\users\raksh\anaconda3\lib\site-packages (from jsonschema>=4.18.0->jupyterlab-server<3,>=2.27.1->notebook>=4.4.1->widgetsnbextension~=3.6.6->ipywidgets) (2023.7.1)
Requirement already satisfied: referencing>=0.28.4 in c:\users\raksh\anaconda3\lib\site-packages (from jsonschema>=4.18.0->jupyterlab-server<3,>=2.27.1->notebook>=4.4.1->widgetsnbextension~=3.6.6->ipywidgets) (0.30.2)
Requirement already satisfied: rpds-py>=0.7.1 in c:\users\raksh\anaconda3\lib\site-packages (from jsonschema>=4.18.0->jupyterlab-server<3,>=2.27.1->notebook>=4.4.1->widgetsnbextension~=3.6.6->ipywidgets) (0.10.6)
Requirement already satisfied: python-dateutil>=2.8.2 in c:\users\raksh\anaconda3\lib\site-packages (from jupyter-client>=7.4.4->jupyter-server<3,>=2.4.0->notebook>=4.4.1->widgetsnbextension~=3.6.6->ipywidgets) (2.9.0.post0)
Requirement already satisfied: platformdirs>=2.5 in c:\users\raksh\anaconda3\lib\site-packages (from jupyter-core!=5.0.*,>=4.12->jupyter-server<3,>=2.4.0->notebook>=4.4.1->widgetsnbextension~=3.6.6->ipywidgets) (3.10.0)
Requirement already satisfied: pywin32>=300 in c:\users\raksh\anaconda3\lib\site-packages (from jupyter-core!=5.0.*,>=4.12->jupyter-server<3,>=2.4.0->notebook>=4.4.1->widgetsnbextension~=3.6.6->ipywidgets) (305.1)
Requirement already satisfied: python-json-logger>=2.0.4 in c:\users\raksh\anaconda3\lib\site-packages (from jupyter-events>=0.9.0->jupyter-server<3,>=2.4.0->notebook>=4.4.1->widgetsnbextension~=3.6.6->ipywidgets) (2.0.7)
Requirement already satisfied: pyyaml>=5.3 in c:\users\raksh\anaconda3\lib\site-packages (from jupyter-events>=0.9.0->jupyter-server<3,>=2.4.0->notebook>=4.4.1->widgetsnbextension~=3.6.6->ipywidgets) (6.0.1)
Requirement already satisfied: rfc3339-validator in c:\users\raksh\anaconda3\lib\site-packages (from jupyter-events>=0.9.0->jupyter-server<3,>=2.4.0->notebook>=4.4.1->widgetsnbextension~=3.6.6->ipywidgets) (0.1.4)
Requirement already satisfied: rfc3986-validator>=0.1.1 in c:\users\raksh\anaconda3\lib\site-packages (from jupyter-events>=0.9.0->jupyter-server<3,>=2.4.0->notebook>=4.4.1->widgetsnbextension~=3.6.6->ipywidgets) (0.1.1)
Requirement already satisfied: beautifulsoup4 in c:\users\raksh\anaconda3\lib\site-packages (from nbconvert>=6.4.4->jupyter-server<3,>=2.4.0->notebook>=4.4.1->widgetsnbextension~=3.6.6->ipywidgets) (4.12.3)
Requirement already satisfied: bleach!=5.0.0 in c:\users\raksh\anaconda3\lib\site-packages (from nbconvert>=6.4.4->jupyter-server<3,>=2.4.0->notebook>=4.4.1->widgetsnbextension~=3.6.6->ipywidgets) (4.1.0)
Requirement already satisfied: defusedxml in c:\users\raksh\anaconda3\lib\site-packages (from nbconvert>=6.4.4->jupyter-server<3,>=2.4.0->notebook>=4.4.1->widgetsnbextension~=3.6.6->ipywidgets) (0.7.1)
Requirement already satisfied: jupyterlab-pygments in c:\users\raksh\anaconda3\lib\site-packages (from nbconvert>=6.4.4->jupyter-server<3,>=2.4.0->notebook>=4.4.1->widgetsnbextension~=3.6.6->ipywidgets) (0.1.2)
Requirement already satisfied: mistune<4,>=2.0.3 in c:\users\raksh\anaconda3\lib\site-packages (from nbconvert>=6.4.4->jupyter-server<3,>=2.4.0->notebook>=4.4.1->widgetsnbextension~=3.6.6->ipywidgets) (2.0.4)
Requirement already satisfied: nbclient>=0.5.0 in c:\users\raksh\anaconda3\lib\site-packages (from nbconvert>=6.4.4->jupyter-server<3,>=2.4.0->notebook>=4.4.1->widgetsnbextension~=3.6.6->ipywidgets) (0.8.0)
Requirement already satisfied: pandocfilters>=1.4.1 in c:\users\raksh\anaconda3\lib\site-packages (from nbconvert>=6.4.4->jupyter-server<3,>=2.4.0->notebook>=4.4.1->widgetsnbextension~=3.6.6->ipywidgets) (1.5.0)
Requirement already satisfied: tinycss2 in c:\users\raksh\anaconda3\lib\site-packages (from nbconvert>=6.4.4->jupyter-server<3,>=2.4.0->notebook>=4.4.1->widgetsnbextension~=3.6.6->ipywidgets) (1.2.1)
Requirement already satisfied: fastjsonschema>=2.15 in c:\users\raksh\anaconda3\lib\site-packages (from nbformat>=5.3.0->jupyter-server<3,>=2.4.0->notebook>=4.4.1->widgetsnbextension~=3.6.6->ipywidgets) (2.16.2)
Requirement already satisfied: charset-normalizer<4,>=2 in c:\users\raksh\anaconda3\lib\site-packages (from requests>=2.31->jupyterlab-server<3,>=2.27.1->notebook>=4.4.1->widgetsnbextension~=3.6.6->ipywidgets) (3.3.2)
Requirement already satisfied: urllib3<3,>=1.21.1 in c:\users\raksh\anaconda3\lib\site-packages (from requests>=2.31->jupyterlab-server<3,>=2.27.1->notebook>=4.4.1->widgetsnbextension~=3.6.6->ipywidgets) (2.2.3)
Requirement already satisfied: webencodings in c:\users\raksh\anaconda3\lib\site-packages (from bleach!=5.0.0->nbconvert>=6.4.4->jupyter-server<3,>=2.4.0->notebook>=4.4.1->widgetsnbextension~=3.6.6->ipywidgets) (0.5.1)
Collecting fqdn (from jsonschema[format-nongpl]>=4.18.0->jupyter-events>=0.9.0->jupyter-server<3,>=2.4.0->notebook>=4.4.1->widgetsnbextension~=3.6.6->ipywidgets)
  Downloading fqdn-1.5.1-py3-none-any.whl.metadata (1.4 kB)
Collecting isoduration (from jsonschema[format-nongpl]>=4.18.0->jupyter-events>=0.9.0->jupyter-server<3,>=2.4.0->notebook>=4.4.1->widgetsnbextension~=3.6.6->ipywidgets)
  Downloading isoduration-20.11.0-py3-none-any.whl.metadata (5.7 kB)
Requirement already satisfied: jsonpointer>1.13 in c:\users\raksh\anaconda3\lib\site-packages (from jsonschema[format-nongpl]>=4.18.0->jupyter-events>=0.9.0->jupyter-server<3,>=2.4.0->notebook>=4.4.1->widgetsnbextension~=3.6.6->ipywidgets) (2.1)
Collecting uri-template (from jsonschema[format-nongpl]>=4.18.0->jupyter-events>=0.9.0->jupyter-server<3,>=2.4.0->notebook>=4.4.1->widgetsnbextension~=3.6.6->ipywidgets)
  Downloading uri_template-1.3.0-py3-none-any.whl.metadata (8.8 kB)
Collecting webcolors>=24.6.0 (from jsonschema[format-nongpl]>=4.18.0->jupyter-events>=0.9.0->jupyter-server<3,>=2.4.0->notebook>=4.4.1->widgetsnbextension~=3.6.6->ipywidgets)
  Downloading webcolors-25.10.0-py3-none-any.whl.metadata (2.2 kB)
Requirement already satisfied: cffi>=1.0.1 in c:\users\raksh\anaconda3\lib\site-packages (from argon2-cffi-bindings->argon2-cffi>=21.1->jupyter-server<3,>=2.4.0->notebook>=4.4.1->widgetsnbextension~=3.6.6->ipywidgets) (1.17.1)
Requirement already satisfied: soupsieve>1.2 in c:\users\raksh\anaconda3\lib\site-packages (from beautifulsoup4->nbconvert>=6.4.4->jupyter-server<3,>=2.4.0->notebook>=4.4.1->widgetsnbextension~=3.6.6->ipywidgets) (2.5)
Requirement already satisfied: pycparser in c:\users\raksh\anaconda3\lib\site-packages (from cffi>=1.0.1->argon2-cffi-bindings->argon2-cffi>=21.1->jupyter-server<3,>=2.4.0->notebook>=4.4.1->widgetsnbextension~=3.6.6->ipywidgets) (2.21)
Requirement already satisfied: arrow>=0.15.0 in c:\users\raksh\anaconda3\lib\site-packages (from isoduration->jsonschema[format-nongpl]>=4.18.0->jupyter-events>=0.9.0->jupyter-server<3,>=2.4.0->notebook>=4.4.1->widgetsnbextension~=3.6.6->ipywidgets) (1.2.3)
Downloading webcolors-25.10.0-py3-none-any.whl (14 kB)
Downloading fqdn-1.5.1-py3-none-any.whl (9.1 kB)
Downloading isoduration-20.11.0-py3-none-any.whl (11 kB)
Downloading uri_template-1.3.0-py3-none-any.whl (11 kB)
Installing collected packages: webcolors, uri-template, fqdn, isoduration
Successfully installed fqdn-1.5.1 isoduration-20.11.0 uri-template-1.3.0 webcolors-25.10.0
Note: you may need to restart the kernel to use updated packages.

In [7]:
!pip install ipywidgets
!jupyter nbextension enable --py widgetsnbextension

Requirement already satisfied: ipywidgets in c:\users\raksh\anaconda3\lib\site-packages (7.8.1)
Requirement already satisfied: comm>=0.1.3 in c:\users\raksh\anaconda3\lib\site-packages (from ipywidgets) (0.2.1)
Requirement already satisfied: ipython-genutils~=0.2.0 in c:\users\raksh\anaconda3\lib\site-packages (from ipywidgets) (0.2.0)
Requirement already satisfied: traitlets>=4.3.1 in c:\users\raksh\anaconda3\lib\site-packages (from ipywidgets) (5.14.3)
Requirement already satisfied: widgetsnbextension~=3.6.6 in c:\users\raksh\anaconda3\lib\site-packages (from ipywidgets) (3.6.6)
Requirement already satisfied: ipython>=4.0.0 in c:\users\raksh\anaconda3\lib\site-packages (from ipywidgets) (8.27.0)
Requirement already satisfied: jupyterlab-widgets<3,>=1.0.0 in c:\users\raksh\anaconda3\lib\site-packages (from ipywidgets) (1.0.0)
Requirement already satisfied: decorator in c:\users\raksh\anaconda3\lib\site-packages (from ipython>=4.0.0->ipywidgets) (5.1.1)
Requirement already satisfied: jedi>=0.16 in c:\users\raksh\anaconda3\lib\site-packages (from ipython>=4.0.0->ipywidgets) (0.19.1)
Requirement already satisfied: matplotlib-inline in c:\users\raksh\anaconda3\lib\site-packages (from ipython>=4.0.0->ipywidgets) (0.1.6)
Requirement already satisfied: prompt-toolkit<3.1.0,>=3.0.41 in c:\users\raksh\anaconda3\lib\site-packages (from ipython>=4.0.0->ipywidgets) (3.0.43)
Requirement already satisfied: pygments>=2.4.0 in c:\users\raksh\anaconda3\lib\site-packages (from ipython>=4.0.0->ipywidgets) (2.15.1)
Requirement already satisfied: stack-data in c:\users\raksh\anaconda3\lib\site-packages (from ipython>=4.0.0->ipywidgets) (0.2.0)
Requirement already satisfied: colorama in c:\users\raksh\anaconda3\lib\site-packages (from ipython>=4.0.0->ipywidgets) (0.4.6)
Requirement already satisfied: notebook>=4.4.1 in c:\users\raksh\anaconda3\lib\site-packages (from widgetsnbextension~=3.6.6->ipywidgets) (7.2.2)
Requirement already satisfied: parso<0.9.0,>=0.8.3 in c:\users\raksh\anaconda3\lib\site-packages (from jedi>=0.16->ipython>=4.0.0->ipywidgets) (0.8.3)
Requirement already satisfied: jupyter-server<3,>=2.4.0 in c:\users\raksh\anaconda3\lib\site-packages (from notebook>=4.4.1->widgetsnbextension~=3.6.6->ipywidgets) (2.14.1)
Requirement already satisfied: jupyterlab-server<3,>=2.27.1 in c:\users\raksh\anaconda3\lib\site-packages (from notebook>=4.4.1->widgetsnbextension~=3.6.6->ipywidgets) (2.27.3)
Requirement already satisfied: jupyterlab<4.3,>=4.2.0 in c:\users\raksh\anaconda3\lib\site-packages (from notebook>=4.4.1->widgetsnbextension~=3.6.6->ipywidgets) (4.2.5)
Requirement already satisfied: notebook-shim<0.3,>=0.2 in c:\users\raksh\anaconda3\lib\site-packages (from notebook>=4.4.1->widgetsnbextension~=3.6.6->ipywidgets) (0.2.3)
Requirement already satisfied: tornado>=6.2.0 in c:\users\raksh\anaconda3\lib\site-packages (from notebook>=4.4.1->widgetsnbextension~=3.6.6->ipywidgets) (6.4.1)
Requirement already satisfied: wcwidth in c:\users\raksh\anaconda3\lib\site-packages (from prompt-toolkit<3.1.0,>=3.0.41->ipython>=4.0.0->ipywidgets) (0.2.5)
Requirement already satisfied: executing in c:\users\raksh\anaconda3\lib\site-packages (from stack-data->ipython>=4.0.0->ipywidgets) (0.8.3)
Requirement already satisfied: asttokens in c:\users\raksh\anaconda3\lib\site-packages (from stack-data->ipython>=4.0.0->ipywidgets) (2.0.5)
Requirement already satisfied: pure-eval in c:\users\raksh\anaconda3\lib\site-packages (from stack-data->ipython>=4.0.0->ipywidgets) (0.2.2)
Requirement already satisfied: anyio>=3.1.0 in c:\users\raksh\anaconda3\lib\site-packages (from jupyter-server<3,>=2.4.0->notebook>=4.4.1->widgetsnbextension~=3.6.6->ipywidgets) (4.2.0)
Requirement already satisfied: argon2-cffi>=21.1 in c:\users\raksh\anaconda3\lib\site-packages (from jupyter-server<3,>=2.4.0->notebook>=4.4.1->widgetsnbextension~=3.6.6->ipywidgets) (21.3.0)
Requirement already satisfied: jinja2>=3.0.3 in c:\users\raksh\anaconda3\lib\site-packages (from jupyter-server<3,>=2.4.0->notebook>=4.4.1->widgetsnbextension~=3.6.6->ipywidgets) (3.1.4)
Requirement already satisfied: jupyter-client>=7.4.4 in c:\users\raksh\anaconda3\lib\site-packages (from jupyter-server<3,>=2.4.0->notebook>=4.4.1->widgetsnbextension~=3.6.6->ipywidgets) (8.6.0)
Requirement already satisfied: jupyter-core!=5.0.*,>=4.12 in c:\users\raksh\anaconda3\lib\site-packages (from jupyter-server<3,>=2.4.0->notebook>=4.4.1->widgetsnbextension~=3.6.6->ipywidgets) (5.7.2)
Requirement already satisfied: jupyter-events>=0.9.0 in c:\users\raksh\anaconda3\lib\site-packages (from jupyter-server<3,>=2.4.0->notebook>=4.4.1->widgetsnbextension~=3.6.6->ipywidgets) (0.10.0)
Requirement already satisfied: jupyter-server-terminals>=0.4.4 in c:\users\raksh\anaconda3\lib\site-packages (from jupyter-server<3,>=2.4.0->notebook>=4.4.1->widgetsnbextension~=3.6.6->ipywidgets) (0.4.4)
Requirement already satisfied: nbconvert>=6.4.4 in c:\users\raksh\anaconda3\lib\site-packages (from jupyter-server<3,>=2.4.0->notebook>=4.4.1->widgetsnbextension~=3.6.6->ipywidgets) (7.16.4)
Requirement already satisfied: nbformat>=5.3.0 in c:\users\raksh\anaconda3\lib\site-packages (from jupyter-server<3,>=2.4.0->notebook>=4.4.1->widgetsnbextension~=3.6.6->ipywidgets) (5.10.4)
Requirement already satisfied: overrides>=5.0 in c:\users\raksh\anaconda3\lib\site-packages (from jupyter-server<3,>=2.4.0->notebook>=4.4.1->widgetsnbextension~=3.6.6->ipywidgets) (7.4.0)
Requirement already satisfied: packaging>=22.0 in c:\users\raksh\anaconda3\lib\site-packages (from jupyter-server<3,>=2.4.0->notebook>=4.4.1->widgetsnbextension~=3.6.6->ipywidgets) (24.1)
Requirement already satisfied: prometheus-client>=0.9 in c:\users\raksh\anaconda3\lib\site-packages (from jupyter-server<3,>=2.4.0->notebook>=4.4.1->widgetsnbextension~=3.6.6->ipywidgets) (0.14.1)
Requirement already satisfied: pywinpty>=2.0.1 in c:\users\raksh\anaconda3\lib\site-packages (from jupyter-server<3,>=2.4.0->notebook>=4.4.1->widgetsnbextension~=3.6.6->ipywidgets) (2.0.10)
Requirement already satisfied: pyzmq>=24 in c:\users\raksh\anaconda3\lib\site-packages (from jupyter-server<3,>=2.4.0->notebook>=4.4.1->widgetsnbextension~=3.6.6->ipywidgets) (25.1.2)
Requirement already satisfied: send2trash>=1.8.2 in c:\users\raksh\anaconda3\lib\site-packages (from jupyter-server<3,>=2.4.0->notebook>=4.4.1->widgetsnbextension~=3.6.6->ipywidgets) (1.8.2)
Requirement already satisfied: terminado>=0.8.3 in c:\users\raksh\anaconda3\lib\site-packages (from jupyter-server<3,>=2.4.0->notebook>=4.4.1->widgetsnbextension~=3.6.6->ipywidgets) (0.17.1)
Requirement already satisfied: websocket-client>=1.7 in c:\users\raksh\anaconda3\lib\site-packages (from jupyter-server<3,>=2.4.0->notebook>=4.4.1->widgetsnbextension~=3.6.6->ipywidgets) (1.8.0)
Requirement already satisfied: async-lru>=1.0.0 in c:\users\raksh\anaconda3\lib\site-packages (from jupyterlab<4.3,>=4.2.0->notebook>=4.4.1->widgetsnbextension~=3.6.6->ipywidgets) (2.0.4)
Requirement already satisfied: httpx>=0.25.0 in c:\users\raksh\anaconda3\lib\site-packages (from jupyterlab<4.3,>=4.2.0->notebook>=4.4.1->widgetsnbextension~=3.6.6->ipywidgets) (0.27.0)
Requirement already satisfied: ipykernel>=6.5.0 in c:\users\raksh\anaconda3\lib\site-packages (from jupyterlab<4.3,>=4.2.0->notebook>=4.4.1->widgetsnbextension~=3.6.6->ipywidgets) (6.28.0)
Requirement already satisfied: jupyter-lsp>=2.0.0 in c:\users\raksh\anaconda3\lib\site-packages (from jupyterlab<4.3,>=4.2.0->notebook>=4.4.1->widgetsnbextension~=3.6.6->ipywidgets) (2.2.0)
Requirement already satisfied: setuptools>=40.1.0 in c:\users\raksh\anaconda3\lib\site-packages (from jupyterlab<4.3,>=4.2.0->notebook>=4.4.1->widgetsnbextension~=3.6.6->ipywidgets) (75.1.0)
Requirement already satisfied: babel>=2.10 in c:\users\raksh\anaconda3\lib\site-packages (from jupyterlab-server<3,>=2.27.1->notebook>=4.4.1->widgetsnbextension~=3.6.6->ipywidgets) (2.11.0)
Requirement already satisfied: json5>=0.9.0 in c:\users\raksh\anaconda3\lib\site-packages (from jupyterlab-server<3,>=2.27.1->notebook>=4.4.1->widgetsnbextension~=3.6.6->ipywidgets) (0.9.6)
Requirement already satisfied: jsonschema>=4.18.0 in c:\users\raksh\anaconda3\lib\site-packages (from jupyterlab-server<3,>=2.27.1->notebook>=4.4.1->widgetsnbextension~=3.6.6->ipywidgets) (4.23.0)
Requirement already satisfied: requests>=2.31 in c:\users\raksh\anaconda3\lib\site-packages (from jupyterlab-server<3,>=2.27.1->notebook>=4.4.1->widgetsnbextension~=3.6.6->ipywidgets) (2.32.3)
Requirement already satisfied: six in c:\users\raksh\anaconda3\lib\site-packages (from asttokens->stack-data->ipython>=4.0.0->ipywidgets) (1.16.0)
Requirement already satisfied: idna>=2.8 in c:\users\raksh\anaconda3\lib\site-packages (from anyio>=3.1.0->jupyter-server<3,>=2.4.0->notebook>=4.4.1->widgetsnbextension~=3.6.6->ipywidgets) (3.7)
Requirement already satisfied: sniffio>=1.1 in c:\users\raksh\anaconda3\lib\site-packages (from anyio>=3.1.0->jupyter-server<3,>=2.4.0->notebook>=4.4.1->widgetsnbextension~=3.6.6->ipywidgets) (1.3.0)
Requirement already satisfied: argon2-cffi-bindings in c:\users\raksh\anaconda3\lib\site-packages (from argon2-cffi>=21.1->jupyter-server<3,>=2.4.0->notebook>=4.4.1->widgetsnbextension~=3.6.6->ipywidgets) (21.2.0)
Requirement already satisfied: pytz>=2015.7 in c:\users\raksh\anaconda3\lib\site-packages (from babel>=2.10->jupyterlab-server<3,>=2.27.1->notebook>=4.4.1->widgetsnbextension~=3.6.6->ipywidgets) (2024.1)
Requirement already satisfied: certifi in c:\users\raksh\anaconda3\lib\site-packages (from httpx>=0.25.0->jupyterlab<4.3,>=4.2.0->notebook>=4.4.1->widgetsnbextension~=3.6.6->ipywidgets) (2025.1.31)
Requirement already satisfied: httpcore==1.* in c:\users\raksh\anaconda3\lib\site-packages (from httpx>=0.25.0->jupyterlab<4.3,>=4.2.0->notebook>=4.4.1->widgetsnbextension~=3.6.6->ipywidgets) (1.0.9)
Requirement already satisfied: h11>=0.16 in c:\users\raksh\anaconda3\lib\site-packages (from httpcore==1.*->httpx>=0.25.0->jupyterlab<4.3,>=4.2.0->notebook>=4.4.1->widgetsnbextension~=3.6.6->ipywidgets) (0.16.0)
Requirement already satisfied: debugpy>=1.6.5 in c:\users\raksh\anaconda3\lib\site-packages (from ipykernel>=6.5.0->jupyterlab<4.3,>=4.2.0->notebook>=4.4.1->widgetsnbextension~=3.6.6->ipywidgets) (1.6.7)
Requirement already satisfied: nest-asyncio in c:\users\raksh\anaconda3\lib\site-packages (from ipykernel>=6.5.0->jupyterlab<4.3,>=4.2.0->notebook>=4.4.1->widgetsnbextension~=3.6.6->ipywidgets) (1.6.0)
Requirement already satisfied: psutil in c:\users\raksh\anaconda3\lib\site-packages (from ipykernel>=6.5.0->jupyterlab<4.3,>=4.2.0->notebook>=4.4.1->widgetsnbextension~=3.6.6->ipywidgets) (5.9.0)
Requirement already satisfied: MarkupSafe>=2.0 in c:\users\raksh\anaconda3\lib\site-packages (from jinja2>=3.0.3->jupyter-server<3,>=2.4.0->notebook>=4.4.1->widgetsnbextension~=3.6.6->ipywidgets) (2.1.3)
Requirement already satisfied: attrs>=22.2.0 in c:\users\raksh\anaconda3\lib\site-packages (from jsonschema>=4.18.0->jupyterlab-server<3,>=2.27.1->notebook>=4.4.1->widgetsnbextension~=3.6.6->ipywidgets) (23.1.0)
Requirement already satisfied: jsonschema-specifications>=2023.03.6 in c:\users\raksh\anaconda3\lib\site-packages (from jsonschema>=4.18.0->jupyterlab-server<3,>=2.27.1->notebook>=4.4.1->widgetsnbextension~=3.6.6->ipywidgets) (2023.7.1)
Requirement already satisfied: referencing>=0.28.4 in c:\users\raksh\anaconda3\lib\site-packages (from jsonschema>=4.18.0->jupyterlab-server<3,>=2.27.1->notebook>=4.4.1->widgetsnbextension~=3.6.6->ipywidgets) (0.30.2)
Requirement already satisfied: rpds-py>=0.7.1 in c:\users\raksh\anaconda3\lib\site-packages (from jsonschema>=4.18.0->jupyterlab-server<3,>=2.27.1->notebook>=4.4.1->widgetsnbextension~=3.6.6->ipywidgets) (0.10.6)
Requirement already satisfied: python-dateutil>=2.8.2 in c:\users\raksh\anaconda3\lib\site-packages (from jupyter-client>=7.4.4->jupyter-server<3,>=2.4.0->notebook>=4.4.1->widgetsnbextension~=3.6.6->ipywidgets) (2.9.0.post0)
Requirement already satisfied: platformdirs>=2.5 in c:\users\raksh\anaconda3\lib\site-packages (from jupyter-core!=5.0.*,>=4.12->jupyter-server<3,>=2.4.0->notebook>=4.4.1->widgetsnbextension~=3.6.6->ipywidgets) (3.10.0)
Requirement already satisfied: pywin32>=300 in c:\users\raksh\anaconda3\lib\site-packages (from jupyter-core!=5.0.*,>=4.12->jupyter-server<3,>=2.4.0->notebook>=4.4.1->widgetsnbextension~=3.6.6->ipywidgets) (305.1)
Requirement already satisfied: python-json-logger>=2.0.4 in c:\users\raksh\anaconda3\lib\site-packages (from jupyter-events>=0.9.0->jupyter-server<3,>=2.4.0->notebook>=4.4.1->widgetsnbextension~=3.6.6->ipywidgets) (2.0.7)
Requirement already satisfied: pyyaml>=5.3 in c:\users\raksh\anaconda3\lib\site-packages (from jupyter-events>=0.9.0->jupyter-server<3,>=2.4.0->notebook>=4.4.1->widgetsnbextension~=3.6.6->ipywidgets) (6.0.1)
Requirement already satisfied: rfc3339-validator in c:\users\raksh\anaconda3\lib\site-packages (from jupyter-events>=0.9.0->jupyter-server<3,>=2.4.0->notebook>=4.4.1->widgetsnbextension~=3.6.6->ipywidgets) (0.1.4)
Requirement already satisfied: rfc3986-validator>=0.1.1 in c:\users\raksh\anaconda3\lib\site-packages (from jupyter-events>=0.9.0->jupyter-server<3,>=2.4.0->notebook>=4.4.1->widgetsnbextension~=3.6.6->ipywidgets) (0.1.1)
Requirement already satisfied: beautifulsoup4 in c:\users\raksh\anaconda3\lib\site-packages (from nbconvert>=6.4.4->jupyter-server<3,>=2.4.0->notebook>=4.4.1->widgetsnbextension~=3.6.6->ipywidgets) (4.12.3)
Requirement already satisfied: bleach!=5.0.0 in c:\users\raksh\anaconda3\lib\site-packages (from nbconvert>=6.4.4->jupyter-server<3,>=2.4.0->notebook>=4.4.1->widgetsnbextension~=3.6.6->ipywidgets) (4.1.0)
Requirement already satisfied: defusedxml in c:\users\raksh\anaconda3\lib\site-packages (from nbconvert>=6.4.4->jupyter-server<3,>=2.4.0->notebook>=4.4.1->widgetsnbextension~=3.6.6->ipywidgets) (0.7.1)
Requirement already satisfied: jupyterlab-pygments in c:\users\raksh\anaconda3\lib\site-packages (from nbconvert>=6.4.4->jupyter-server<3,>=2.4.0->notebook>=4.4.1->widgetsnbextension~=3.6.6->ipywidgets) (0.1.2)
Requirement already satisfied: mistune<4,>=2.0.3 in c:\users\raksh\anaconda3\lib\site-packages (from nbconvert>=6.4.4->jupyter-server<3,>=2.4.0->notebook>=4.4.1->widgetsnbextension~=3.6.6->ipywidgets) (2.0.4)
Requirement already satisfied: nbclient>=0.5.0 in c:\users\raksh\anaconda3\lib\site-packages (from nbconvert>=6.4.4->jupyter-server<3,>=2.4.0->notebook>=4.4.1->widgetsnbextension~=3.6.6->ipywidgets) (0.8.0)
Requirement already satisfied: pandocfilters>=1.4.1 in c:\users\raksh\anaconda3\lib\site-packages (from nbconvert>=6.4.4->jupyter-server<3,>=2.4.0->notebook>=4.4.1->widgetsnbextension~=3.6.6->ipywidgets) (1.5.0)
Requirement already satisfied: tinycss2 in c:\users\raksh\anaconda3\lib\site-packages (from nbconvert>=6.4.4->jupyter-server<3,>=2.4.0->notebook>=4.4.1->widgetsnbextension~=3.6.6->ipywidgets) (1.2.1)
Requirement already satisfied: fastjsonschema>=2.15 in c:\users\raksh\anaconda3\lib\site-packages (from nbformat>=5.3.0->jupyter-server<3,>=2.4.0->notebook>=4.4.1->widgetsnbextension~=3.6.6->ipywidgets) (2.16.2)
Requirement already satisfied: charset-normalizer<4,>=2 in c:\users\raksh\anaconda3\lib\site-packages (from requests>=2.31->jupyterlab-server<3,>=2.27.1->notebook>=4.4.1->widgetsnbextension~=3.6.6->ipywidgets) (3.3.2)
Requirement already satisfied: urllib3<3,>=1.21.1 in c:\users\raksh\anaconda3\lib\site-packages (from requests>=2.31->jupyterlab-server<3,>=2.27.1->notebook>=4.4.1->widgetsnbextension~=3.6.6->ipywidgets) (2.2.3)
Requirement already satisfied: webencodings in c:\users\raksh\anaconda3\lib\site-packages (from bleach!=5.0.0->nbconvert>=6.4.4->jupyter-server<3,>=2.4.0->notebook>=4.4.1->widgetsnbextension~=3.6.6->ipywidgets) (0.5.1)
Requirement already satisfied: fqdn in c:\users\raksh\anaconda3\lib\site-packages (from jsonschema[format-nongpl]>=4.18.0->jupyter-events>=0.9.0->jupyter-server<3,>=2.4.0->notebook>=4.4.1->widgetsnbextension~=3.6.6->ipywidgets) (1.5.1)
Requirement already satisfied: isoduration in c:\users\raksh\anaconda3\lib\site-packages (from jsonschema[format-nongpl]>=4.18.0->jupyter-events>=0.9.0->jupyter-server<3,>=2.4.0->notebook>=4.4.1->widgetsnbextension~=3.6.6->ipywidgets) (20.11.0)
Requirement already satisfied: jsonpointer>1.13 in c:\users\raksh\anaconda3\lib\site-packages (from jsonschema[format-nongpl]>=4.18.0->jupyter-events>=0.9.0->jupyter-server<3,>=2.4.0->notebook>=4.4.1->widgetsnbextension~=3.6.6->ipywidgets) (2.1)
Requirement already satisfied: uri-template in c:\users\raksh\anaconda3\lib\site-packages (from jsonschema[format-nongpl]>=4.18.0->jupyter-events>=0.9.0->jupyter-server<3,>=2.4.0->notebook>=4.4.1->widgetsnbextension~=3.6.6->ipywidgets) (1.3.0)
Requirement already satisfied: webcolors>=24.6.0 in c:\users\raksh\anaconda3\lib\site-packages (from jsonschema[format-nongpl]>=4.18.0->jupyter-events>=0.9.0->jupyter-server<3,>=2.4.0->notebook>=4.4.1->widgetsnbextension~=3.6.6->ipywidgets) (25.10.0)
Requirement already satisfied: cffi>=1.0.1 in c:\users\raksh\anaconda3\lib\site-packages (from argon2-cffi-bindings->argon2-cffi>=21.1->jupyter-server<3,>=2.4.0->notebook>=4.4.1->widgetsnbextension~=3.6.6->ipywidgets) (1.17.1)
Requirement already satisfied: soupsieve>1.2 in c:\users\raksh\anaconda3\lib\site-packages (from beautifulsoup4->nbconvert>=6.4.4->jupyter-server<3,>=2.4.0->notebook>=4.4.1->widgetsnbextension~=3.6.6->ipywidgets) (2.5)
Requirement already satisfied: pycparser in c:\users\raksh\anaconda3\lib\site-packages (from cffi>=1.0.1->argon2-cffi-bindings->argon2-cffi>=21.1->jupyter-server<3,>=2.4.0->notebook>=4.4.1->widgetsnbextension~=3.6.6->ipywidgets) (2.21)
Requirement already satisfied: arrow>=0.15.0 in c:\users\raksh\anaconda3\lib\site-packages (from isoduration->jsonschema[format-nongpl]>=4.18.0->jupyter-events>=0.9.0->jupyter-server<3,>=2.4.0->notebook>=4.4.1->widgetsnbextension~=3.6.6->ipywidgets) (1.2.3)

usage: jupyter [-h] [--version] [--config-dir] [--data-dir] [--runtime-dir]
               [--paths] [--json] [--debug]
               [subcommand]

Jupyter: Interactive Computing

positional arguments:
  subcommand     the subcommand to launch

options:
  -h, --help     show this help message and exit
  --version      show the versions of core jupyter packages and exit
  --config-dir   show Jupyter config dir
  --data-dir     show Jupyter data dir
  --runtime-dir  show Jupyter runtime dir
  --paths        show all Jupyter paths. Add --json for machine-readable
                 format.
  --json         output paths as machine-readable json
  --debug        output debug information about paths

Available subcommands: console dejavu events execute kernel kernelspec lab
labextension labhub migrate nbconvert notebook qtconsole run script server
troubleshoot trust

Jupyter command `jupyter-nbextension` not found.

In [11]:
!pip install sentence-transformers

Requirement already satisfied: sentence-transformers in c:\users\raksh\anaconda3\lib\site-packages (5.2.0)
Requirement already satisfied: transformers<6.0.0,>=4.41.0 in c:\users\raksh\anaconda3\lib\site-packages (from sentence-transformers) (4.57.3)
Requirement already satisfied: tqdm in c:\users\raksh\anaconda3\lib\site-packages (from sentence-transformers) (4.66.5)
Requirement already satisfied: torch>=1.11.0 in c:\users\raksh\anaconda3\lib\site-packages (from sentence-transformers) (2.9.1)
Requirement already satisfied: scikit-learn in c:\users\raksh\anaconda3\lib\site-packages (from sentence-transformers) (1.5.1)
Requirement already satisfied: scipy in c:\users\raksh\anaconda3\lib\site-packages (from sentence-transformers) (1.13.1)
Requirement already satisfied: huggingface-hub>=0.20.0 in c:\users\raksh\anaconda3\lib\site-packages (from sentence-transformers) (0.36.0)
Requirement already satisfied: typing_extensions>=4.5.0 in c:\users\raksh\anaconda3\lib\site-packages (from sentence-transformers) (4.15.0)
Requirement already satisfied: filelock in c:\users\raksh\anaconda3\lib\site-packages (from huggingface-hub>=0.20.0->sentence-transformers) (3.13.1)
Requirement already satisfied: fsspec>=2023.5.0 in c:\users\raksh\anaconda3\lib\site-packages (from huggingface-hub>=0.20.0->sentence-transformers) (2024.6.1)
Requirement already satisfied: packaging>=20.9 in c:\users\raksh\anaconda3\lib\site-packages (from huggingface-hub>=0.20.0->sentence-transformers) (24.1)
Requirement already satisfied: pyyaml>=5.1 in c:\users\raksh\anaconda3\lib\site-packages (from huggingface-hub>=0.20.0->sentence-transformers) (6.0.1)
Requirement already satisfied: requests in c:\users\raksh\anaconda3\lib\site-packages (from huggingface-hub>=0.20.0->sentence-transformers) (2.32.3)
Requirement already satisfied: sympy>=1.13.3 in c:\users\raksh\anaconda3\lib\site-packages (from torch>=1.11.0->sentence-transformers) (1.14.0)
Requirement already satisfied: networkx>=2.5.1 in c:\users\raksh\anaconda3\lib\site-packages (from torch>=1.11.0->sentence-transformers) (3.3)
Requirement already satisfied: jinja2 in c:\users\raksh\anaconda3\lib\site-packages (from torch>=1.11.0->sentence-transformers) (3.1.4)
Requirement already satisfied: setuptools in c:\users\raksh\anaconda3\lib\site-packages (from torch>=1.11.0->sentence-transformers) (75.1.0)
Requirement already satisfied: colorama in c:\users\raksh\anaconda3\lib\site-packages (from tqdm->sentence-transformers) (0.4.6)
Requirement already satisfied: numpy>=1.17 in c:\users\raksh\anaconda3\lib\site-packages (from transformers<6.0.0,>=4.41.0->sentence-transformers) (1.26.4)
Requirement already satisfied: regex!=2019.12.17 in c:\users\raksh\anaconda3\lib\site-packages (from transformers<6.0.0,>=4.41.0->sentence-transformers) (2024.9.11)
Requirement already satisfied: tokenizers<=0.23.0,>=0.22.0 in c:\users\raksh\anaconda3\lib\site-packages (from transformers<6.0.0,>=4.41.0->sentence-transformers) (0.22.1)
Requirement already satisfied: safetensors>=0.4.3 in c:\users\raksh\anaconda3\lib\site-packages (from transformers<6.0.0,>=4.41.0->sentence-transformers) (0.7.0)
Requirement already satisfied: joblib>=1.2.0 in c:\users\raksh\anaconda3\lib\site-packages (from scikit-learn->sentence-transformers) (1.4.2)
Requirement already satisfied: threadpoolctl>=3.1.0 in c:\users\raksh\anaconda3\lib\site-packages (from scikit-learn->sentence-transformers) (3.5.0)
Requirement already satisfied: mpmath<1.4,>=1.1.0 in c:\users\raksh\anaconda3\lib\site-packages (from sympy>=1.13.3->torch>=1.11.0->sentence-transformers) (1.3.0)
Requirement already satisfied: MarkupSafe>=2.0 in c:\users\raksh\anaconda3\lib\site-packages (from jinja2->torch>=1.11.0->sentence-transformers) (2.1.3)
Requirement already satisfied: charset-normalizer<4,>=2 in c:\users\raksh\anaconda3\lib\site-packages (from requests->huggingface-hub>=0.20.0->sentence-transformers) (3.3.2)
Requirement already satisfied: idna<4,>=2.5 in c:\users\raksh\anaconda3\lib\site-packages (from requests->huggingface-hub>=0.20.0->sentence-transformers) (3.7)
Requirement already satisfied: urllib3<3,>=1.21.1 in c:\users\raksh\anaconda3\lib\site-packages (from requests->huggingface-hub>=0.20.0->sentence-transformers) (2.2.3)
Requirement already satisfied: certifi>=2017.4.17 in c:\users\raksh\anaconda3\lib\site-packages (from requests->huggingface-hub>=0.20.0->sentence-transformers) (2025.1.31)

In [ ]:
from sentence_transformers import SentenceTransformer

encoder = SentenceTransformer("all-mpnet-base-v2")
vectors = encoder.encode(df["text"])

print(len(vectors))
print(vectors[0][:10])   # first 10 embedding values

Xet Storage is enabled for this repo, but the 'hf_xet' package is not installed. Falling back to regular HTTP download. For better performance, install the package with: `pip install huggingface_hub[hf_xet]` or `pip install hf_xet`

model.safetensors:  36%|###5      | 157M/438M [00:00<?, ?B/s]

In [1]:
pip install hf_xet

Collecting hf_xet
  Using cached hf_xet-1.2.0-cp37-abi3-win_amd64.whl.metadata (5.0 kB)
Downloading hf_xet-1.2.0-cp37-abi3-win_amd64.whl (2.9 MB)
   ---------------------------------------- 0.0/2.9 MB ? eta -:--:--
   --- ------------------------------------ 0.3/2.9 MB ? eta -:--:--
   ------- -------------------------------- 0.5/2.9 MB 1.5 MB/s eta 0:00:02
   ---------- ----------------------------- 0.8/2.9 MB 1.2 MB/s eta 0:00:02
   -------------- ------------------------- 1.0/2.9 MB 1.4 MB/s eta 0:00:02
   --------------------- ------------------ 1.6/2.9 MB 1.6 MB/s eta 0:00:01
   ---------------------------- ----------- 2.1/2.9 MB 1.8 MB/s eta 0:00:01
   -------------------------------- ------- 2.4/2.9 MB 1.8 MB/s eta 0:00:01
   ---------------------------------------- 2.9/2.9 MB 1.8 MB/s eta 0:00:00
Installing collected packages: hf_xet
Successfully installed hf_xet-1.2.0
Note: you may need to restart the kernel to use updated packages.

In [3]:
pip install huggingface_hub[hf_xet]

Requirement already satisfied: huggingface_hub[hf_xet] in c:\users\raksh\anaconda3\lib\site-packages (0.36.0)
Requirement already satisfied: filelock in c:\users\raksh\anaconda3\lib\site-packages (from huggingface_hub[hf_xet]) (3.13.1)
Requirement already satisfied: fsspec>=2023.5.0 in c:\users\raksh\anaconda3\lib\site-packages (from huggingface_hub[hf_xet]) (2024.6.1)
Requirement already satisfied: packaging>=20.9 in c:\users\raksh\anaconda3\lib\site-packages (from huggingface_hub[hf_xet]) (24.1)
Requirement already satisfied: pyyaml>=5.1 in c:\users\raksh\anaconda3\lib\site-packages (from huggingface_hub[hf_xet]) (6.0.1)
Requirement already satisfied: requests in c:\users\raksh\anaconda3\lib\site-packages (from huggingface_hub[hf_xet]) (2.32.3)
Requirement already satisfied: tqdm>=4.42.1 in c:\users\raksh\anaconda3\lib\site-packages (from huggingface_hub[hf_xet]) (4.66.5)
Requirement already satisfied: typing-extensions>=3.7.4.3 in c:\users\raksh\anaconda3\lib\site-packages (from huggingface_hub[hf_xet]) (4.15.0)
Requirement already satisfied: hf-xet<2.0.0,>=1.1.2 in c:\users\raksh\anaconda3\lib\site-packages (from huggingface_hub[hf_xet]) (1.2.0)
Requirement already satisfied: colorama in c:\users\raksh\anaconda3\lib\site-packages (from tqdm>=4.42.1->huggingface_hub[hf_xet]) (0.4.6)
Requirement already satisfied: charset-normalizer<4,>=2 in c:\users\raksh\anaconda3\lib\site-packages (from requests->huggingface_hub[hf_xet]) (3.3.2)
Requirement already satisfied: idna<4,>=2.5 in c:\users\raksh\anaconda3\lib\site-packages (from requests->huggingface_hub[hf_xet]) (3.7)
Requirement already satisfied: urllib3<3,>=1.21.1 in c:\users\raksh\anaconda3\lib\site-packages (from requests->huggingface_hub[hf_xet]) (2.2.3)
Requirement already satisfied: certifi>=2017.4.17 in c:\users\raksh\anaconda3\lib\site-packages (from requests->huggingface_hub[hf_xet]) (2025.1.31)
Note: you may need to restart the kernel to use updated packages.

In [5]:
encoder = SentenceTransformer("all-mpnet-base-v2")
vectors = encoder.encode(df.text)

NameError: name 'SentenceTransformer' is not defined

In [7]:
# Install package (runs only if not installed)
import sys
!{sys.executable} -m pip install sentence-transformers

# Restart-safe import
from sentence_transformers import SentenceTransformer
import pandas as pd

# Sample dataframe (use this if df is not already created)
data = {
    "text": [
        "Meditation and yoga can improve mental health",
        "Fruits and vegetables help control blood pressure",
        "Latest fashion trends this week"
    ]
}
df = pd.DataFrame(data)

# Create encoder and embeddings
encoder = SentenceTransformer("all-mpnet-base-v2")
vectors = encoder.encode(df["text"])

print("SUCCESS ✅")
print("Number of vectors:", len(vectors))
print("Vector size:", len(vectors[0]))

Requirement already satisfied: sentence-transformers in c:\users\raksh\anaconda3\lib\site-packages (5.2.0)
Requirement already satisfied: transformers<6.0.0,>=4.41.0 in c:\users\raksh\anaconda3\lib\site-packages (from sentence-transformers) (4.57.3)
Requirement already satisfied: tqdm in c:\users\raksh\anaconda3\lib\site-packages (from sentence-transformers) (4.66.5)
Requirement already satisfied: torch>=1.11.0 in c:\users\raksh\anaconda3\lib\site-packages (from sentence-transformers) (2.9.1)
Requirement already satisfied: scikit-learn in c:\users\raksh\anaconda3\lib\site-packages (from sentence-transformers) (1.5.1)
Requirement already satisfied: scipy in c:\users\raksh\anaconda3\lib\site-packages (from sentence-transformers) (1.13.1)
Requirement already satisfied: huggingface-hub>=0.20.0 in c:\users\raksh\anaconda3\lib\site-packages (from sentence-transformers) (0.36.0)
Requirement already satisfied: typing_extensions>=4.5.0 in c:\users\raksh\anaconda3\lib\site-packages (from sentence-transformers) (4.15.0)
Requirement already satisfied: filelock in c:\users\raksh\anaconda3\lib\site-packages (from huggingface-hub>=0.20.0->sentence-transformers) (3.13.1)
Requirement already satisfied: fsspec>=2023.5.0 in c:\users\raksh\anaconda3\lib\site-packages (from huggingface-hub>=0.20.0->sentence-transformers) (2024.6.1)
Requirement already satisfied: packaging>=20.9 in c:\users\raksh\anaconda3\lib\site-packages (from huggingface-hub>=0.20.0->sentence-transformers) (24.1)
Requirement already satisfied: pyyaml>=5.1 in c:\users\raksh\anaconda3\lib\site-packages (from huggingface-hub>=0.20.0->sentence-transformers) (6.0.1)
Requirement already satisfied: requests in c:\users\raksh\anaconda3\lib\site-packages (from huggingface-hub>=0.20.0->sentence-transformers) (2.32.3)
Requirement already satisfied: sympy>=1.13.3 in c:\users\raksh\anaconda3\lib\site-packages (from torch>=1.11.0->sentence-transformers) (1.14.0)
Requirement already satisfied: networkx>=2.5.1 in c:\users\raksh\anaconda3\lib\site-packages (from torch>=1.11.0->sentence-transformers) (3.3)
Requirement already satisfied: jinja2 in c:\users\raksh\anaconda3\lib\site-packages (from torch>=1.11.0->sentence-transformers) (3.1.4)
Requirement already satisfied: setuptools in c:\users\raksh\anaconda3\lib\site-packages (from torch>=1.11.0->sentence-transformers) (75.1.0)
Requirement already satisfied: colorama in c:\users\raksh\anaconda3\lib\site-packages (from tqdm->sentence-transformers) (0.4.6)
Requirement already satisfied: numpy>=1.17 in c:\users\raksh\anaconda3\lib\site-packages (from transformers<6.0.0,>=4.41.0->sentence-transformers) (1.26.4)
Requirement already satisfied: regex!=2019.12.17 in c:\users\raksh\anaconda3\lib\site-packages (from transformers<6.0.0,>=4.41.0->sentence-transformers) (2024.9.11)
Requirement already satisfied: tokenizers<=0.23.0,>=0.22.0 in c:\users\raksh\anaconda3\lib\site-packages (from transformers<6.0.0,>=4.41.0->sentence-transformers) (0.22.1)
Requirement already satisfied: safetensors>=0.4.3 in c:\users\raksh\anaconda3\lib\site-packages (from transformers<6.0.0,>=4.41.0->sentence-transformers) (0.7.0)
Requirement already satisfied: joblib>=1.2.0 in c:\users\raksh\anaconda3\lib\site-packages (from scikit-learn->sentence-transformers) (1.4.2)
Requirement already satisfied: threadpoolctl>=3.1.0 in c:\users\raksh\anaconda3\lib\site-packages (from scikit-learn->sentence-transformers) (3.5.0)
Requirement already satisfied: mpmath<1.4,>=1.1.0 in c:\users\raksh\anaconda3\lib\site-packages (from sympy>=1.13.3->torch>=1.11.0->sentence-transformers) (1.3.0)
Requirement already satisfied: MarkupSafe>=2.0 in c:\users\raksh\anaconda3\lib\site-packages (from jinja2->torch>=1.11.0->sentence-transformers) (2.1.3)
Requirement already satisfied: charset-normalizer<4,>=2 in c:\users\raksh\anaconda3\lib\site-packages (from requests->huggingface-hub>=0.20.0->sentence-transformers) (3.3.2)
Requirement already satisfied: idna<4,>=2.5 in c:\users\raksh\anaconda3\lib\site-packages (from requests->huggingface-hub>=0.20.0->sentence-transformers) (3.7)
Requirement already satisfied: urllib3<3,>=1.21.1 in c:\users\raksh\anaconda3\lib\site-packages (from requests->huggingface-hub>=0.20.0->sentence-transformers) (2.2.3)
Requirement already satisfied: certifi>=2017.4.17 in c:\users\raksh\anaconda3\lib\site-packages (from requests->huggingface-hub>=0.20.0->sentence-transformers) (2025.1.31)

model.safetensors:   0%|          | 0.00/438M [00:00<?, ?B/s]

C:\Users\raksh\anaconda3\Lib\site-packages\huggingface_hub\file_download.py:143: UserWarning: `huggingface_hub` cache-system uses symlinks by default to efficiently store duplicated files but your machine does not support them in C:\Users\raksh\.cache\huggingface\hub\models--sentence-transformers--all-mpnet-base-v2. Caching files will still work but in a degraded version that might require more space on your disk. This warning can be disabled by setting the `HF_HUB_DISABLE_SYMLINKS_WARNING` environment variable. For more details, see https://huggingface.co/docs/huggingface_hub/how-to-cache#limitations.
To support symlinks on Windows, you either need to activate Developer Mode or to run Python as an administrator. In order to activate developer mode, see this article: https://docs.microsoft.com/en-us/windows/apps/get-started/enable-your-device-for-development
  warnings.warn(message)

tokenizer_config.json:   0%|          | 0.00/363 [00:00<?, ?B/s]

vocab.txt: 0.00B [00:00, ?B/s]

tokenizer.json: 0.00B [00:00, ?B/s]

special_tokens_map.json:   0%|          | 0.00/239 [00:00<?, ?B/s]

config.json:   0%|          | 0.00/190 [00:00<?, ?B/s]

SUCCESS ✅
Number of vectors: 3
Vector size: 768

In [7]:
from sentence_transformers import SentenceTransformer

In [12]:
from sentence_transformers import SentenceTransformer
import pandas as pd

# Create dataframe
df = pd.DataFrame({
    "text": [
        "Meditation and yoga can improve mental health",
        "Fruits, whole grains and vegetables helps control blood pressure",
        "These are the latest fashion trends for this week",
        "Vibrant color jeans for male are becoming a trend",
        "The concert starts at 7 PM tonight",
        "Navaratri dandiya program at Expo center in Mumbai this october",
        "Exciting vacation destinations for your next trip",
        "Maldives and Srilanka are gaining popularity in terms of low budget vacation places"
    ]
})

# Create embeddings
encoder = SentenceTransformer("all-mpnet-base-v2")
vectors = encoder.encode(df["text"])

print("SUCCESS ✅")
print("Number of vectors:", len(vectors))
print("Vector dimension:", len(vectors[0]))

SUCCESS ✅
Number of vectors: 8
Vector dimension: 768

In [16]:
encoder = SentenceTransformer("all-mpnet-base-v2")
vectors = encoder.encode(df.text)

In [18]:
vectors.shape

(8, 768)

In [20]:
dim = vectors.shape[1]
dim

768

In [1]:


import faiss

index = faiss.IndexFlatL2(dim)

NameError: name 'dim' is not defined

In [3]:
import faiss
import numpy as np
from sentence_transformers import SentenceTransformer
import pandas as pd

df = pd.DataFrame({
    "text": [
        "Meditation and yoga can improve mental health",
        "Fruits and vegetables help control blood pressure"
    ]
})

encoder = SentenceTransformer("all-mpnet-base-v2")
vectors = encoder.encode(df["text"])

dim = vectors.shape[1]
index = faiss.IndexFlatL2(dim)

index.add(np.array(vectors).astype("float32"))

print("FAISS index created with", index.ntotal, "vectors")

FAISS index created with 2 vectors

In [1]:

import faiss

index = faiss.IndexFlatL2(dim)

NameError: name 'dim' is not defined

In [3]:
dim = vectors.shape[1]   # get embedding dimension
index = faiss.IndexFlatL2(dim)

NameError: name 'vectors' is not defined

In [5]:
import faiss
import numpy as np
from sentence_transformers import SentenceTransformer
import pandas as pd

df = pd.DataFrame({
    "text": [
        "Meditation and yoga can improve mental health",
        "Fruits and vegetables help control blood pressure"
    ]
})

encoder = SentenceTransformer("all-mpnet-base-v2")
vectors = encoder.encode(df["text"])

dim = vectors.shape[1]
index = faiss.IndexFlatL2(dim)

index.add(np.array(vectors).astype("float32"))

print("FAISS index created with", index.ntotal, "vectors")

FAISS index created with 2 vectors

In [11]:
dim = vectors.shape[1]   # get embedding dimension
index = faiss.IndexFlatL2(dim)

In [13]:


index.add(vectors)

In [15]:
index

In [17]:


search_query = "I want to buy a polo t-shirt"
# search_query = "looking for places to visit during the holidays"
# search_query = "An apple a day keeps the doctor away"
vec = encoder.encode(search_query)
vec.shape

(768,)

In [19]:


import numpy as np
svec = np.array(vec).reshape(1,-1)
svec.shape

(1, 768)

In [21]:
distances, I = index.search(new_vec, k=2)
distances

NameError: name 'new_vec' is not defined

In [1]:
import numpy as np

query = "health related topics"

# Encode query (IMPORTANT: wrap in list)
new_vec = encoder.encode([query])

# Convert to float32
new_vec = np.array(new_vec).astype("float32")

NameError: name 'encoder' is not defined

In [4]:
# ===== IMPORTS =====
import numpy as np
import pandas as pd
import faiss
from sentence_transformers import SentenceTransformer

# ===== DATAFRAME =====
df = pd.DataFrame({
    "text": [
        "Meditation and yoga can improve mental health",
        "Fruits, whole grains and vegetables helps control blood pressure",
        "These are the latest fashion trends for this week",
        "Vibrant color jeans for male are becoming a trend",
        "The concert starts at 7 PM tonight",
        "Navaratri dandiya program at Expo center in Mumbai this october",
        "Exciting vacation destinations for your next trip",
        "Maldives and Srilanka are gaining popularity in terms of low budget vacation places"
    ]
})

# ===== ENCODER =====
encoder = SentenceTransformer("all-mpnet-base-v2")

# ===== EMBEDDINGS =====
vectors = encoder.encode(df["text"])
vectors = np.array(vectors).astype("float32")

# ===== FAISS INDEX =====
dim = vectors.shape[1]
index = faiss.IndexFlatL2(dim)
index.add(vectors)

# ===== SEARCH QUERY =====
query = "health related topics"
new_vec = encoder.encode([query])
new_vec = np.array(new_vec).astype("float32")

distances, I = index.search(new_vec, k=2)

print("Distances:", distances)
print("Results:")
for idx in I[0]:
    print("-", df.iloc[idx]["text"])

Distances: [[1.3447886 1.479914 ]]
Results:
- Meditation and yoga can improve mental health
- Fruits, whole grains and vegetables helps control blood pressure

In [7]:
distances, I = index.search(new_vec, k=2)
distances

NameError: name 'index' is not defined

In [5]:
I

NameError: name 'I' is not defined

In [3]:
I.tolist()

NameError: name 'I' is not defined

In [1]:
row_indices = I.tolist()[0]
row_indices

NameError: name 'I' is not defined